export const strategyLearningStyles: Record<string, string> = {
  visual_array: 'visual',
  ones: 'pattern',
  tens: 'pattern',
  twos: 'pattern',
  pure_doubles: 'kinesthetic',
  fives_half_of_ten: 'pattern',
  fives_nickel_counting: 'kinesthetic',
  elevens_simple: 'pattern',
  squares: 'pattern',
  nines: 'pattern',
  nines_digit_sum: 'pattern',
  nines_finger_trick: 'kinesthetic',
  near_doubles: 'pattern',
  benchmark_numbers: 'kinesthetic',
  building_known_facts: 'kinesthetic',
  elevens_advanced: 'pattern',
  memory_trick: 'auditory',
  skip_counting: 'auditory',
  decomposition: 'kinesthetic',
};
