export const strategyLearningStyles: Record<string, string> = {
  visual_array: 'visual',
  ones: 'pattern',
  tens: 'pattern',
  twos: 'pattern',
  pure_doubles: 'breakdown',
  fives_half_of_ten: 'breakdown',
  fives_nickel_counting: 'counting',
  elevens_simple: 'pattern',
  squares: 'pattern',
  nines: 'pattern',
  nines_digit_sum: 'pattern',
  nines_finger_trick: 'kinesthetic',
  near_doubles: 'breakdown',
  benchmark_numbers: 'breakdown',
  rounding_and_adjusting: 'breakdown',
  building_known_facts: 'breakdown',
  left_to_right: 'breakdown',
  elevens_advanced: 'breakdown',
  memory_trick: 'auditory',
  skip_counting: 'counting',
  decomposition: 'breakdown',
};
